# LLM 配置
llm:
  provider: "dashscope"  # dashscope | openai | anthropic

  # DashScope (通义千问) 配置
  dashscope:
    api_key: "${DASHSCOPE_API_KEY}"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    chat_model: "qwen-turbo"  # qwen-turbo | qwen-plus | qwen-max
    temperature: 0.7
    max_tokens: 4096

  # OpenAI 配置
  openai:
    api_key: "${OPENAI_API_KEY?}"  # 可选，未设置时为空
    base_url: "https://api.openai.com/v1"
    chat_model: "gpt-4o-mini"
    temperature: 0.7
    max_tokens: 4096

  # Anthropic 配置
  anthropic:
    api_key: "${ANTHROPIC_API_KEY?}"  # 可选，未设置时为空
    chat_model: "claude-3-5-sonnet-20241022"
    temperature: 0.7
    max_tokens: 4096

# Embedding 配置
embedding:
  provider: "dashscope"  # dashscope | openai

  dashscope:
    api_key: "${DASHSCOPE_API_KEY}"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model: "text-embedding-v3"

  openai:
    api_key: "${OPENAI_API_KEY?}"  # 可选，未设置时为空
    base_url: "https://api.openai.com/v1"
    model: "text-embedding-3-small"

# 检索配置
retrieval:
  strategy: "hybrid"  # cosine | hybrid | llm_assisted
  default_top_k: 1
  max_top_k: 10
  min_score_threshold: 0.85  # 最小相关度阈值，低于此值的记忆不会被返回

  # Hybrid 策略配置
  hybrid:
    weights:
      semantic: 0.6      # 语义相似度权重
      confidence: 0.2    # 置信度权重
      success: 0.15      # 成功偏好权重
      recency: 0.05      # 时效性权重
    time_decay_halflife: 30  # 时间衰减半衰期（天）

# 存储配置
storage:
  backend: "json"  # json | sqlite | chroma

  json:
    memories_path: "~/.reasoningbank/data/memories.json"
    embeddings_path: "~/.reasoningbank/data/embeddings.json"
    archived_path: "~/.reasoningbank/data/archived_memories.json"
#    memories_path: "/Users/hanw/data/memories.json"
#    embeddings_path: "/Users/hanw/data/embeddings.json"

  sqlite:
    db_path: "~/.reasoningbank/data/reasoning_bank.db"

# 记忆提取配置
extraction:
  max_memories_per_trajectory: 3  # 每个轨迹最多提取记忆数
  judge_temperature: 0.0          # 判断轨迹成功/失败的温度
  extract_temperature: 1.0        # 提取记忆的温度
  async_by_default: true          # 默认异步处理

# MCP 服务器配置
server:
  name: "reasoning-bank"
  version: "0.1.0"
  log_level: "INFO"  # DEBUG | INFO | WARNING | ERROR

# 记忆管理配置
memory_manager:
  enabled: true  # 是否启用记忆管理器

  # 去重配置
  deduplication:
    strategy: "semantic"  # semantic (语义去重)
    on_extraction: true   # 在提取时实时去重

    # 语义去重配置
    semantic:
      threshold: 0.90           # 相似度阈值（0-1）
      top_k_check: 1            # 检查最相似的前K条记忆

  # 合并配置
  merge:
    strategy: "llm"  # llm | voting | template
    auto_execute: true  # 自动执行合并（后台）

    # 触发条件
    trigger:
      min_similar_count: 3         # 最少相似记忆数
      similarity_threshold: 0.85   # 相似度阈值

    # LLM合并配置
    llm:
      temperature: 0.7

    # Voting合并配置
    voting:
      min_group_size: 2

    # 原记忆处理
    original_handling: "archive"  # archive | delete | mark
    archive:
      keep_embeddings: false  # 归档时是否保留embedding

